[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = false

[client]
showErrorDetails = true
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#CC0000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#1a202c"
font = "sans serif"

[logger]
level = "info"
