[server]
headless = false
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
enableWebsocketCompression = false
address = "localhost"
port = 8502

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = false

[client]
showErrorDetails = true
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#CC0000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#1a202c"
font = "sans serif"

[logger]
level = "info"
